apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivial-go-web-app-ingress
spec:
  rules:
  - http:
      paths:
        - path: /active
          pathType: Prefix
          backend:
            service:
              name: rollout-bluegreen-active
              port:
                number: 8080
        - path: /preview
          pathType: Prefix
          backend:
            service:
              name: rollout-bluegreen-preview
              port:
                number: 8080