apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivial-go-web-app-ingress
  labels:
    app: trivial-go-web-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
        - path: /active
          pathType: Prefix
          backend:
            service:
              name: rollout-bluegreen-active
              port:
                number: 8080
        - path: /preview
          pathType: Prefix
          backend:
            service:
              name: rollout-bluegreen-preview
              port:
                number: 8080
